### ISSUE TITLE
CKAN Version numbers need a bump

### ISSUE THREAD

**Issue by cmcaine** [severedsolo/CleverSat#1]
CleverSats isn't listed for version 1.1.2

Great work on all your mods! Thanks very much!

**Comment by severedsolo** [comment]
I'm waiting for 1.1.3 to be released first

**Comment by cmcaine** [comment]
Looking at the miniAVC code and ckan docs, it looks like you could just
omit the ksp_version_max patch value and the tools will interpret the
mod as matching all 1.1.x releases.

Maybe you already know that and don't want to do it anyway.
