### ISSUE TITLE
Contracts do not activate

### ISSUE THREAD

**Issue by Fumblesneeze** [severedsolo/CleverSat#5]
CleverSat Contracts do not activate for me because the requirements for any of the solar panels is not met, although they are unlocked. I'm using Ven's Stock Part Revamp, is this an incompatibility?

When I go to the VAB and go Filter by Module and select "Deployable Solar Panel" I have several unlocked parts available.

(RNG likes me, too)

**Comment by tivec** [comment]
If you are using Kopernicus, you will probably have found the same issue as I am faced with. CleverSat does not have a parameter for Kopernicus version of the solar panels.

**Comment by Fumblesneeze** [comment]
Can confirm that this patch works (yes I do have Kopernicus installed).

**Comment by severedsolo** [comment]
This has probably been fixed with #8
